### ISSUE TITLE
Doesn't build with IAR compiler

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-os-example-atecc608a#15]

**Comment by 0xc0170** [comment]
I've quickly checked the upstream repo, I could not find the compilation issues reported there. Are they aware the library does not build with IAR/ARMCC?

**Comment by Patater** [comment]
https://github.com/MicrochipTech/cryptoauthlib/issues/116

**Comment by TaniaMirzin** [comment]
@Patater  @jenia81 Bryan Hunt suggested an addition that allows IAR support.

**Comment by Patater** [comment]
Re-opening as this is not completely fixed yet.

See the MicrochipTech issue for details
https://github.com/MicrochipTech/cryptoauthlib/issues/116#issuecomment-582920812

**Comment by Patater** [comment]
Cryptoauthlib added a new "app" which doesn't build with IAR at the same time they fixed the library to build with IAR. By mbed-ignoring the new app, which we don't use, this example is working on IAR.

Fixed via https://github.com/ARMmbed/mbed-os-example-atecc608a/pull/39
