### ISSUE TITLE
Other prerequisites undefined?

### ISSUE THREAD

**Issue by mdroberts1243** [ARMmbed/mbed-os-example-atecc608a#26]
I am able to build on mbed-cli for the K64F as per the example but the program fails to link when I tried NUCLEO_L476RG and NUCLEO_L432KC (the two boards I have on hand).

The issue seems to be the PSA stuff.  Prior to getting to the linking stage I had a number of problems with #include "psa/xxx" lines as well.

New to mbed-os, but it seems there are other prerequsites unmentioned...

> Link: atecc608a

> BUILD/NUCLEO_L476RG/GCC_ARM/main.o: In function `run_tests':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\main.c:380: undefined reference to `mbed_psa_reboot_and_request_new_security_state'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\main.c:403: undefined reference to `mbed_psa_reboot_and_request_new_security_state'
> BUILD/NUCLEO_L476RG/GCC_ARM/main.o: In function `main':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\main.c:613: undefined reference to `mbed_psa_reboot_and_request_new_security_state'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_start_key_creation':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1612: undefined reference to `psa_crypto_save_transaction'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1615: undefined reference to `psa_crypto_stop_transaction'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1615: undefined reference to `psa_crypto_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_finish_key_creation':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1707: undefined reference to `psa_destroy_persistent_key'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1645: undefined reference to `psa_crypto_transaction'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1710: undefined reference to `psa_crypto_stop_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_fail_key_creation':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1753: undefined reference to `psa_crypto_stop_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_crypto_init':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:5660: undefined reference to `psa_crypto_load_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.o: In function `psa_load_se_persistent_data':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto_se.c:166: undefined reference to `psa_its_get'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.o: In function `psa_save_se_persistent_data':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto_se.c:185: undefined reference to `psa_its_set'
> collect2.exe: error: ld returned 1 exit status
> [ERROR] BUILD/NUCLEO_L476RG/GCC_ARM/main.o: In function `run_tests':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\main.c:380: undefined reference to `mbed_psa_reboot_and_request_new_security_state'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\main.c:403: undefined reference to `mbed_psa_reboot_and_request_new_security_state'
> BUILD/NUCLEO_L476RG/GCC_ARM/main.o: In function `main':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\main.c:613: undefined reference to `mbed_psa_reboot_and_request_new_security_state'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_start_key_creation':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1612: undefined reference to `psa_crypto_save_transaction'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1615: undefined reference to `psa_crypto_stop_transaction'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1615: undefined reference to `psa_crypto_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_finish_key_creation':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1707: undefined reference to `psa_destroy_persistent_key'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1645: undefined reference to `psa_crypto_transaction'
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1710: undefined reference to `psa_crypto_stop_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_fail_key_creation':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:1753: undefined reference to `psa_crypto_stop_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.o: In function `psa_crypto_init':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto.c:5660: undefined reference to `psa_crypto_load_transaction'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.o: In function `psa_load_se_persistent_data':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto_se.c:166: undefined reference to `psa_its_get'
> BUILD/NUCLEO_L476RG/GCC_ARM/mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.o: In function `psa_save_se_persistent_data':
> C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a/.\mbed-os\features\mbedtls\mbed-crypto\platform\COMPONENT_PSA_SRV_IMPL/psa_crypto_se.c:185: undefined reference to `psa_its_set'
> collect2.exe: error: ld returned 1 exit status
> 
> [mbed] ERROR: "c:\program files\python37\python.exe" returned error.
>        Code: 1
>        Path: "C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a"
>        Command: "c:\program files\python37\python.exe -u C:\Users\mdrob\mbed-os-example-atecc608a\atecc608a\mbed-os\tools\make.py -t GCC_ARM -m NUCLEO_L476RG --source . --build .\BUILD\NUCLEO_L476RG\GCC_ARM"
>        Tip: You could retry the last command with "-v" flag for verbose output
> ---

**Comment by mdroberts1243** [comment]
Hi, I tried again with a fresh installation of mbed-cli on a Linux laptop.  K64F worked fine, but the unmodified source returns this error for the two NUCLEO boards:

> (MBED) mark@mdr-debian:~/mbed-os-example-atecc608a/atecc608a$ mbed compile -t GCC_ARM -m NUCLEO_L476RG --flash --sterm
> [mbed] Working path "/home/mark/mbed-os-example-atecc608a/atecc608a" (library)
> [mbed] Program path "/home/mark/mbed-os-example-atecc608a/atecc608a"
> Building project atecc608a (NUCLEO_L476RG, GCC_ARM)
> Scan: atecc608a
> Compile [  0.1%]: main.c
> [Fatal Error] main.c@25,10: psa/lifecycle.h: No such file or directory
> [ERROR] ./main.c:25:10: fatal error: psa/lifecycle.h: No such file or directory
>    25 | #include "psa/lifecycle.h"
>       |          ^~~~~~~~~~~~~~~~~
> compilation terminated.
> 
> [mbed] ERROR: "/home/mark/MBED/bin/python2" returned error.
>        Code: 1
>        Path: "/home/mark/mbed-os-example-atecc608a/atecc608a"
>        Command: "/home/mark/MBED/bin/python2 -u /home/mark/mbed-os-example-atecc608a/atecc608a/mbed-os/tools/make.py -t GCC_ARM -m NUCLEO_L476RG --source . --build ./BUILD/NUCLEO_L476RG/GCC_ARM"
>        Tip: You could retry the last command with "-v" flag for verbose output
> ---
> 
>

**Comment by ciarmcom** [comment]
@mdroberts1243 thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@mdroberts1243 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3108*

**Comment by LDong-Arm** [comment]
@mdroberts1243 Sorry for the latest reply, I just came across this page today. The two targets you tried do not currently support PSA in Mbed OS. Only a small number of targets (incl. K64F you mentioned) support PSA.
Please feel free to reopen the issue if you need more help on this, thanks.
